-- MySQL Script generated by MySQL Workbench
-- Wed Jul 25 16:12:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema todoNorte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todoNorte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todoNorte` DEFAULT CHARACTER SET utf8 ;
USE `todoNorte` ;

-- -----------------------------------------------------
-- Table `todoNorte`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nombre` VARCHAR(45) NOT NULL,
  `usu_apellidos` VARCHAR(45) NULL,
  `usu_rut` INT NOT NULL,
  `usu_dv` CHAR(1) NOT NULL,
  `usu_correo` VARCHAR(100) NOT NULL,
  `usu_clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Proveedor` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_nombre` VARCHAR(45) NOT NULL,
  `pro_apellidos` VARCHAR(45) NOT NULL,
  `pro_rut` VARCHAR(45) NOT NULL,
  `pro_dv` CHAR(1) NOT NULL,
  `pro_direccion` VARCHAR(45) NOT NULL,
  `pro_comuna` VARCHAR(45) NOT NULL,
  `pro_banco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`FormaPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`FormaPago` (
  `for_id` INT NOT NULL AUTO_INCREMENT,
  `for_abono` INT NULL,
  `for_fecha` DATE NOT NULL,
  `for_numero` INT NOT NULL,
  `for_tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`for_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Factura` (
  `fac_numero` INT NOT NULL,
  `fac_valorNeto` INT NOT NULL,
  `fac_iva` INT NOT NULL,
  `fac_glosa` VARCHAR(200) NOT NULL,
  `fac_for_pago` INT NOT NULL,
  PRIMARY KEY (`fac_numero`, `fac_for_pago`),
  INDEX `fk_Factura_FormaPago_idx` (`fac_for_pago` ASC),
  CONSTRAINT `fk_Factura_FormaPago`
    FOREIGN KEY (`fac_for_pago`)
    REFERENCES `todoNorte`.`FormaPago` (`for_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Compra` (
  `com_id` INT NOT NULL AUTO_INCREMENT,
  `com_codigoProducto` INT NOT NULL,
  `com_iva` INT NOT NULL,
  `com_valorTotal` INT NOT NULL,
  `com_numeroFactura` INT NOT NULL,
  `com_recargo` INT NOT NULL,
  `com_pro_id` INT NOT NULL,
  `com_for_id` INT NOT NULL,
  PRIMARY KEY (`com_id`, `com_pro_id`, `com_for_id`),
  INDEX `fk_Compra_Proveedor1_idx` (`com_pro_id` ASC),
  INDEX `fk_Compra_FormaPago1_idx` (`com_for_id` ASC),
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`com_pro_id`)
    REFERENCES `todoNorte`.`Proveedor` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_FormaPago1`
    FOREIGN KEY (`com_for_id`)
    REFERENCES `todoNorte`.`FormaPago` (`for_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Cliente` (
  `cli_id` INT NOT NULL AUTO_INCREMENT,
  `cli_nombre` VARCHAR(100) NOT NULL,
  `cli_apellidos` VARCHAR(100) NOT NULL,
  `cli_rut` VARCHAR(45) NOT NULL,
  `cli_dv` CHAR(1) NOT NULL,
  `cli_direccion` VARCHAR(45) NOT NULL,
  `cli_telefono` VARCHAR(45) NOT NULL,
  `cli_giro` VARCHAR(45) NOT NULL,
  `cli_nombreFantasia` VARCHAR(100) NOT NULL,
  `cli_estado` CHAR(1) NOT NULL,
  `cli_correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cli_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Materiales` (
  `mat_id` INT NOT NULL,
  `mat_nombre` VARCHAR(45) NOT NULL,
  `mat_valor` VARCHAR(45) NOT NULL,
  `mat_ccOcupados` INT NULL,
  PRIMARY KEY (`mat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`Trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Trabajo` (
  `tra_id` INT NOT NULL AUTO_INCREMENT,
  `tra_nombre` VARCHAR(45) NOT NULL,
  `tra_cantidad` INT NOT NULL,
  `tra_precioUnitario` INT NOT NULL,
  `tra_medida` INT NOT NULL,
  `tra_metrosLineales` INT NOT NULL,
  `tra_valorRollo` INT NOT NULL,
  `tra_cli_id` INT NOT NULL,
  `tra_mat_id` INT NOT NULL,
  PRIMARY KEY (`tra_id`, `tra_cli_id`, `tra_mat_id`),
  INDEX `fk_Trabajo_Cliente1_idx` (`tra_cli_id` ASC),
  INDEX `fk_Trabajo_Materiales1_idx` (`tra_mat_id` ASC),
  CONSTRAINT `fk_Trabajo_Cliente1`
    FOREIGN KEY (`tra_cli_id`)
    REFERENCES `todoNorte`.`Cliente` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajo_Materiales1`
    FOREIGN KEY (`tra_mat_id`)
    REFERENCES `todoNorte`.`Materiales` (`mat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`CostosFijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`CostosFijos` (
  `cos_id` INT NOT NULL,
  `cos_valorDespacho` INT NOT NULL,
  `cos_arriendo` VARCHAR(45) NOT NULL,
  `cos_servicio` VARCHAR(45) NULL,
  PRIMARY KEY (`cos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todoNorte`.`Horas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todoNorte`.`Horas` (
  `hor_id` INT NOT NULL,
  `hor_valorHorasSub` INT NOT NULL,
  `hor_horasTrabajadas` INT NOT NULL,
  `hor_valorHoraHombre` INT NOT NULL,
  `hor_totalHoras` INT NOT NULL,
  `hor_tra_id` INT NOT NULL,
  PRIMARY KEY (`hor_id`, `hor_tra_id`),
  INDEX `fk_Horas_Trabajo1_idx` (`hor_tra_id` ASC),
  CONSTRAINT `fk_Horas_Trabajo1`
    FOREIGN KEY (`hor_tra_id`)
    REFERENCES `todoNorte`.`Trabajo` (`tra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
